### ISSUE TITLE
Cannot selectively choose hash columns

### ISSUE THREAD

**Issue by aaronjd** [keif888/SSISMHash#11]
I'm working on a newer SSIS project using version of VS 2017 SSDT (Version 15.5.2) targeting SQL Server 2017. The machine has Windows 2012 R2 Datacenter. I am using 1.7.2.0 of Multiple Hash. I cannot selectively choose hash columns to include in the hash. I am only able to select all columns in the column header.

![image](https://user-images.githubusercontent.com/31477724/37619835-9a9a201c-2b88-11e8-9499-52315516ac6d.png)

**Comment by keif888** [comment]
Tested on Windows 10, Microsoft Visual Studio Enterprise 2017, Version 15.5.7 (SSDT 15.1.61710.120) and is working correctly.
I will have to build a system to your spec above to test.

Please note that many years ago I encountered similar issues with a specific build of Windows Server, which was fixed in a later service pack.

**Comment by aaronjd** [comment]
Thanks! Let me know if there is anything else I can provide.

**Comment by keif888** [comment]
Just built the server, and installed VS2017 SSDT 15.5.2.
Looks like there is an issue with the VS2017 SSDT, as it does NOT register the SQL2017 registry settings, or for that matter install the SQL2017 files.
As such the SSISMHash installer can't detect that SQL2017 is on the system, and chooses not to install the DLL's for SQL2017.
I did a custom install including the SQL2017 DLL's.

Subsequent testing has shown no issues.
![image](https://user-images.githubusercontent.com/13086300/37770032-ce47fa2c-2e1e-11e8-9085-11436e284c56.png)
![image](https://user-images.githubusercontent.com/13086300/37770095-fa568976-2e1e-11e8-9ef9-1a753de9f6da.png)

**Comment by keif888** [comment]
I just noticed that the version that I installed is a slightly higher build number than the one that you had installed.  Can you please test with the latest version of SSDT's?

**Comment by aaronjd** [comment]
Awesome. I'll test and verify with latest version.

**Comment by aaronjd** [comment]
Thanks, that worked.
