### ISSUE TITLE
Installation to Azure SSIS runtime

### ISSUE THREAD

**Issue by ElectricLlama** [keif888/SSISMHash#13]
I am trying to install this component to the Azure SSIS runtime.

I'm following the instructions from here:
https://docs.microsoft.com/en-us/azure/data-factory/how-to-configure-azure-ssis-ir-custom-setup

I have a main.cmd file with this in it (on one line):

`msiexec /i MultipleHashInstallerx64.msi /qn /lv %CUSTOM_SETUP_SCRIPT_LOG_DIR%\MultipleHashInstall.LOG`

I can see the MultipleHashInstall.LOG appearing in blob storage (attached) and is populated with a lot of stuff that looks like it's installing. The Azure SSIS runtime starts OK (it won't start if there is an installation error)

With regards to the packages, I have installed the 32 bit version of MultipleHash on my workstation, opened and upgraded my packages in SSDT 15.5.7 and also set the deployment target to SQL 2017

I've deployed to SSIS Azure but I get these in the SSIS log when running in SSIS Azure:

> Load Staging Purchase:Error:   The managed pipeline component "MultipleHash" could not be   loaded.  The exception was: Could not   load type 'MultipleHash' from assembly 'Microsoft.SqlServer.PipelineHost,   Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'..

> Load Staging Billing:Error: The component metadata for "MD5 Hash" could not be upgraded to the newer version of the component. The PerformUpgrade method failed.

> Load Staging Billing:Error: The component is missing, not registered, not upgradeable, or missing required interfaces. The contact information for this component is "http://ssismhash.codeplex.com/".

> Load Staging Billing:Error: Component MD5 Hash, clsid {8DC69D45-2AD5-40C6-AAEC-25722F92D6FC} failed to initialize due to error 0xC0047067 "The "%1" failed to cache the 

> Load Staging Billing:Error:   Component MD5 Hash, clsid {8DC69D45-2AD5-40C6-AAEC-25722F92D6FC} failed to   initialize due to error 0xC0047067 "The "%1" failed to cache   the component metadata object and returned error code 0x%2!8.8X!.".

>Load Staging Billing:Error: The   "MD5 Hash" failed to cache the component metadata object and   returned error code 0x80131600.
> Load Staging Billing:Error: The   managed pipeline component "MultipleHash" could not be loaded.  The exception was: Could not load type   'MultipleHash' from assembly 'Microsoft.SqlServer.PipelineHost, Version=14.0.0.0,   Culture=neutral, PublicKeyToken=89845dcd8080cc91'..

I see an upgrade message in there - I don't understand why it's trying to upgrade.

In the DTSX, 
`PackageFormatVersion=8`
`LastModifiedProductVersion=14.0`

I've tried both the 32 and 64 bit installers.

[MultipleHashInstall.LOG](https://github.com/keif888/SSISMHash/files/2080455/MultipleHashInstall.LOG)

**Comment by keif888** [comment]
Your attached log file is from the 64 bit installer, which is the correct installer for the Azure environment.
Multiple Hash has been installed, to the correct locations (64 bit, 32 bit and the GAC) from what I can see in the log.

I have not attempted to run my component in Azure, and will have to build a test from the ground up.

The 1st SSIS execution error message you are getting implies that Azure SSIS can't find the DLL in the GAC.
The upgrade message is about attempting to upgrade the version of multiple hash being utilised within the SSIS package to the latest version.  Can you please locate the section in the DTSX file which contains the string

`name="UserComponentTypeName">Martin.SQLServer.Dts.MultipleHash`

and check up from there for the content similar to the following:
```
<component
              refId="Package\Data Flow Task\Multiple Hash"
              componentClassID="Microsoft.ManagedComponentHost"
              contactInfo="http://ssismhash.codeplex.com/"
              description="Creates Multiple Hash's from selected input columns."
              name="Multiple Hash"
              version="7">
```
I am interested in what the version number there is, and expect it to be 7, as shown here.

**Comment by keif888** [comment]
Further investigation, after building my own Azure setup, has shown that the installer is detecting where the 64bit files need to go, but not detecting 64bit SSIS.
32bit SSIS is being detected.
Looks like an installer update will be required to make my component work in Azure.

**Comment by keif888** [comment]
Latest release (1.7.3.0) corrects this issue.
You will need to replace the 64 bit MSI installer in your Blob Container within your storage account, and then stop and restart your Azure-SSIS Integration Runtime.

I have tested that the installer is functioning correctly, and that Multiple Hash will execute when running a package against Azure-SSIS.

The following command can be added to you main.cmd to list all the places where MultipleHash has been installed:
`dir c:\multiple*.dll /s > %CUSTOM_SETUP_SCRIPT_LOG_DIR%\checking.log`
There should be three locations:
c:\Program Files\Microsoft SQL Server\140\DTS\PipelineComponents
c:\Program Files (x86)\Microsoft SQL Server\140\DTS\PipelineComponents
c:\Windows\Microsoft.NET\assembly\GAC_MSIL\MultipleHash2017\v4.0_1.0.0.0__51c551904274ab44

**Comment by ElectricLlama** [comment]
Wow, thanks very much. I do appreciate your fast response. I checked the contents of my .dtsx (actually the one on the ispac I deployed) and yes it's version 7. Perhaps that part of the error is a red herring. Unfortunately, my Azure runtime started ignoring my custom install container (no new logs written to it) and will not load the new install. So I deleted and readded my runtime with a new SAS URI and now I get "Gateway Timeout". FYI, here is a comment I raised against the Microsoft doc: https://github.com/MicrosoftDocs/azure-docs/issues/9830#event-1669174608 for which I am also getting a good response.

**Comment by keif888** [comment]
Reopened until confirmed installer is now working for other than my test cases.

**Comment by ElectricLlama** [comment]
Sorry kief, I may not get a chance to retest this. However please note the other thread I linked to - apparently MSIEXEC doesn't support ".\" in the ,msi path. In other words .msi files have to be in the root container.

**Comment by ElectricLlama** [comment]
Thanks for looking at this. I can confirm the component installed correctly to the Azure runtime. I used the following in my main.cmd file: 

```batch
msiexec /i MultipleHash\MultipleHashInstallerx64.msi /qn /lv %CUSTOM_SETUP_SCRIPT_LOG_DIR%\MultipleHashInstall.LOG
```
