### ISSUE TITLE
Installation location of Multiple Hash transform non-default SQL Server install location

### ISSUE THREAD

**Issue by IamOzymandias** [keif888/SSISMHash#16]
I modified the location of my SQL Server 2017 installation directory (I made it the same folder, but on the D drive). The Multi-Hash installer installed to the C Drive. When I copied the DLLs to the corresponding folder on the D Drive, the transform appeared in VS 2017 as expected.

**Comment by keif888** [comment]
That is not supposed to happen.  The installer is supposed to detect where the installation of SQL Server has been done.

Can you please check the content of the following registry keys?

SOFTWARE\Microsoft\Microsoft SQL Server\140\SSIS\Setup\DTSPath Key (Default)
SOFTWARE\Microsoft\Microsoft SQL Server\140\DTS\Setup Key SQLPath

The installer checks these registry locations, and gets the path from them.
If neither exists, it defaults to [ProgramFiles64Folder]\Microsoft SQL Server\140\DTS, which appears to be what has happened.

**Comment by IamOzymandias** [comment]
Both keys's value is: D:\Program Files\Microsoft SQL Server\140\DTS\

**Comment by keif888** [comment]
Is it possible for you to uninstall the component (and delete the files you manually copied), and re-install it with logging turned on in the installer, and upload that installation log file?

eg. (change the log location as appropriate)

`msiexec /i "MultipleHashInstallerx64.msi" /L*V "D:\log\MultipleHashInstall.log"`

If you can't upload the entire file, I am interested in the section that starts:

`Action 22:50:27: AppSearch. Searching for installed applications`

and finishes with (the time will be different)

`Action ended 22:50:28: AppSearch. Return value 1.`

This is where it logs what it finds in the registry.

**Comment by IamOzymandias** [comment]
I can do that later today or this evening.

**Comment by IamOzymandias** [comment]
For what it's worth...but, this may be the designed behavior. I'll still upload the log info later..

My HKLM has these paths and keys. However, HKCU does not. For example, HKCU stopped at the following path, and there was no DTS version of that path.

**\HKEY_CURRENT_USER\Software\Microsoft\Microsoft SQL Server\140\SSIS**

**Comment by keif888** [comment]
I have built a clean server with SQL 2017 only installed onto D:.  This has shown a defect in the installer, as it incorrectly identifies that SQL 2017 is not present.  But, it did correctly identify the installation locations., as shown in a custom install.
Could you please clarify what else is installed on your server?
Is SSDT's installed, or another edition of SQL Server?

**Comment by keif888** [comment]
I have just released a new installer that corrects the issue where SSIS folders exist on C:, but are not the correct installation locations..  
[Release v1.7.4.0](https://github.com/keif888/SSISMHash/releases/tag/V1.7.4.0)

Please try this installer, and confirm that it corrects the issue you encountered.
