### ISSUE TITLE
Anyway to migrate from 2008 to 2017 ?

### ISSUE THREAD

**Issue by lchubdata** [keif888/SSISMHash#18]
Hello,
We are updating 232+ SSIS Packages from VS 2008 to VS 2017.  Is there a way to migrate the SSISMHash 2008 to 2017 without having to re-create and map from scratch in the dataflow the SSISMHash 2017 ?
I tried to mess around the package XML code to change the SSISMHash properties but it did not work.
Thanks
Laurent

**Comment by keif888** [comment]
To upgrade from an older VS version to the latest VS version to do the following:

1. Install the latest VS version
2. Install SSDT's SSIS components
3. Install/Re-install SSISMHash, ensuring that it has detected the appropriate SSIS version
4. Install/Re-install any other SSIS components that you use in your OLDER VS version packages (using the appropriate versions for the target SSIS versions)
5. Backup the older VS version SSIS packages and project files
6. Load latest VS version, and confirm that it has recognised that the required SSIS components are available (including SSISMHash)
7. Load the older VS version SSIS project, which should upgrade automatically.

At least it works that way in all my testing...


If you have upgraded the VS2008 packages to VS2017 WITHOUT a VS2017 compatible version of SSISMHash installed, then you will have issues (like errors stating the SSISMHash is not installed).  I strongly recommend, reverting to the VS2008 SSIS packages, and re-upgrading after installing SSISMHAsh.  Attempting to manually upgrade the metadata will be difficult..

**Comment by lchubdata** [comment]
Hello Keith,

Thanks for your answer it works perfectly.  Our mistake was to migrate the
package to VS2017 without the compatible version of SSISMhash…you were
right.
Regards,
Laurent



*De :* Keith Martin <notifications@github.com>
*Envoyé :* mercredi 9 janvier 2019 08:18
*À :* keif888/SSISMHash <SSISMHash@noreply.github.com>
*Cc :* lchubdata <laurent.cohen@hubdata.fr>; Author <
author@noreply.github.com>
*Objet :* Re: [keif888/SSISMHash] Anyway to migrate from 2008 to 2017 ?
(#18)



To upgrade from an older VS version to the latest VS version to do the
following:

   1. Install the latest VS version
   2. Install SSDT's SSIS components
   3. Install/Re-install SSISMHash, ensuring that it has detected the
   appropriate SSIS version
   4. Install/Re-install any other SSIS components that you use in your
   OLDER VS version packages (using the appropriate versions for the target
   SSIS versions)
   5. Backup the older VS version SSIS packages and project files
   6. Load latest VS version, and confirm that it has recognised that the
   required SSIS components are available (including SSISMHash)
   7. Load the older VS version SSIS project, which should upgrade
   automatically.

At least it works that way in all my testing...

If you have upgraded the VS2008 packages to VS2017 WITHOUT a VS2017
compatible version of SSISMHash installed, then you will have issues (like
errors stating the SSISMHash is not installed). I strongly recommend,
reverting to the VS2008 SSIS packages, and re-upgrading after installing
SSISMHAsh. Attempting to manually upgrade the metadata will be difficult..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keif888/SSISMHash/issues/18#issuecomment-452596093>,
or mute
the thread
