### ISSUE TITLE
SQL Server 2019 Support

### ISSUE THREAD

**Issue by Sr1983** [keif888/SSISMHash#19]
Hello, are you planning SSISMHash support for SQL 2019?

**Comment by keif888** [comment]
Yes.
Code is in Git now, but project has the wrong .Net Framework.  I have to install .Net 4.6.2 and recompile, then test the DLL and the installer.

**Comment by cmongiovi** [comment]
Thanks for your support!

**Comment by cmongiovi** [comment]
Hello,
will be available a new release with compiled installers? 
Thanks again.

**Comment by keif888** [comment]
I am having issues with getting an install onto a client with only VS2019 and SSIS tools installed to detect SQL 2019 correctly.  Working on it right now.
