### ISSUE TITLE
Incorrect version showing in About menu

### ISSUE THREAD

**Issue by wakiongo** [keif888/SSISMHash#22]
I recently updated to the latest multiple hash version - 1.7.5. However, it still shows as version 1.7.2. on the about menu.
I uninstalled the older version and installed this new version but the about menu still shows 1.7.2

I am using visual studio 2015 with projects targetserver version = 2016
<img width="288" alt="MHash 1_7_5" src="https://user-images.githubusercontent.com/111894542/186199914-8a7ac61c-f34a-4b16-b42d-0e0cea255289.png">

Is this a known issue?

**Comment by keif888** [comment]
The last updated date and version are hard coded on the About page, and I forgot to update them.
"This component was last updated by Keith Martin in September 2017.  This is version 1.7.2.0
To download the latest version or get help go to:"
You can double check the actual version number from Add Remove programs, which should show the installed version when you click on the Multiple Hash installed module.

**Comment by wakiongo** [comment]
Thank you @keif888 for getting back on this so promptly.

**Comment by keif888** [comment]
Bug fixed in 1.7.6.0, which will be released after testing is complete

**Comment by keif888** [comment]
V 1.7.6.0 released which fixes this
