### ISSUE TITLE
Sha2(512) Value different in ADF/Snowflake than in SSIS

### ISSUE THREAD

**Issue by Daniel-JM-Rouleau** [keif888/SSISMHash#25]
We are generating the checksum of a combination of two columns (ID an int containing 1002, ContactMethod a varchar containing ‘Email’).

**SSIS** 
The sha512 checksum generated with SSIS Multiple Hash through SSIS is 1F32BFEA7D50117E2036E9CACF06FC24FB8F483B5BDD2C094C395DD88247D546E02678D898FD64227236C24D95746275510653012545D480E6D2A9B00D808C31

**ADF/Snowflake**
The sha2(512( checksum generated through ADF and Snowflake are identical but different than the one generated through SSIS above.
select sha2('10002Email',512);
4cb3b1d676eb2750b0d0f38b5fbf8c6267578cb4c70e450bbf9e923c5932aa7b59b97f59865f610f2ed53247483f7c0f7237150c4e9d0324791ea9ec9425cb0e

Does anyone know what is going on? Our suspicion is the string used as input in SSIS may be decorated with delimiters and be different than ‘10002Email’. Any insight would be greatly appreciated.

We are migrating from SSIS/SQL Server to ADF/Snowflake.

**Comment by keif888** [comment]
You have the option safeNullHandling enabled (which it is by default), and the data that is hashed has a null detection string appended to the end of the data to be hashed.  That null handling string is why the two hashes mentioned above are different.
The code that does the data to be hashed work is here:
https://github.com/keif888/SSISMHash/blob/33fbb5f4ee2bd1cc94b9f294a10db834d2f69256/MultipleHash2008/Utility.cs#L835

Integers are not converted to text before hashing.

In your case the data being hashed would have been 12 bytes long and represented here in hex:
12270000456d61696c4e4e35
https://emn178.github.io/online-tools/sha512.html can be used to take a hex representation of bytes and hash it.

This is made up as follows:
an Int32 converted from 10002 to bytes (shown here in hex) 12270000
a string converted from Email to bytes (shown here in hex) 456d61696c
a null detection string converted from NN5 to bytes (shown here in hex)  4e4e35

The null detection string will have an N or Y for each field that is being hashed, followed where the field is variable length, with a number which is in text format.  For your example there are 2 fields, and integer which is fixed length and not null, and a string which is variable length of 5 and not null.
