### ISSUE TITLE
Multiple Hash transform not available anymore after installing SSDT 17.1 with VS2015

### ISSUE THREAD

**Issue by Henny001** [keif888/SSISMHash#3]
Hi,

After installing SSDT17.1 (build 14.0.61705.170) on a machine with VS2015 already installed, the Multiple Hash component is missing from the SSIS Toolbox. Packages that we're created earlier using this transform still execute fine but can't be modified anymore. 

The packages are targeted to run at SQL Server 2016.

Is it possible to get an update for the Multiple Hash Transform using SSDT17.1 ?

**Comment by KrishnaSQL** [comment]
Yes.. I had the same issue and unable to open the component so can't make any changes .. will this issue be fixed soon or any suggestion to resolve the issue?

**Comment by keif888** [comment]
Issue confirmed on clean installation of SSDT 17.1, using embedded VS2015.
Component doesn't show up when targeting SQL vNext (as expected as it's not supported), or 2016.
It does show up when targeting 2012 or 2014.

When changing target from 2012 or 2014 to 2016, the underlying metadata in the SSIS package is updated correctly.

**Debug (execute SSIS package) for 2016 target WORKS with SSIS Multiple Hash.
You just can not make any changes**


Works on SSDT's prior to 17.1...

Workaround:
Change to targeting SQL 2014, to make updates.  Then change back to targeting SQL 2016.

I do NOT know why SSDT's 17.1 is not finding the component, but I will continue to investigate.

**Comment by keif888** [comment]
This has been fixed with Release 1.6.7.4.

**Comment by Henny001** [comment]
Can confirm that release 1.6.7.4 fixes the issue mentioned after installing SSDT 17.1 in our development environment . Many thanks for the effort taken.
