### ISSUE TITLE
SSDT 17.2 compatibility

### ISSUE THREAD

**Issue by relob** [keif888/SSISMHash#6]
Hi - I wondered if you have any plans to support the latest version of SSDT (17.2) with your MultipleHash component in Visual Studio 2015?

Regards,
Matt Boler

**Comment by keif888** [comment]
SSDT 17.2 works for all, except SQL 2017. (at least in my testing it does)
SQL 2017 support will be a couple of weeks off, and will be a beta release, until such time as SQL 2017 is released.

**Comment by relob** [comment]
Thanks for getting back to me. After I installed 17.2 I no longer had access to the SSISMHash component in SSIS. Tried to reinstall SSISMHash but it still didn't appear in SSIS so went back to SSDT 16. Must be something with my configuration. 

Great product btw - have been using it since Sql2008r2. 

Regards 
Matt Boler

**Comment by keif888** [comment]
Release 1.7.2.0 has been made.  I believe that this addresses the issue encountered.  Please raise another issue if this is not the case.

FYI:
I believe that the component not showing up was because the default in SSDT 17.2 is SQL 2017, which wasn't supported int 1.7.1.0.
