### ISSUE TITLE
SQL 2016 SP1 Support

### ISSUE THREAD

**Issue by jbargallo** [keif888/SSISMHash#8]
Hi Keith,

Reading the changelog history since 1.6.6.4 where you started supporting SQL 2016 _RTM_ I don't see any mention for SQL 2016 _SP1_. Our new SQL 2016 environment is up-to-date (SP1 CU4) and will be following an strict updating policy, so before installing I just wanted to be sure that your latest version solution is supported or on the contrary, if you need to test and especifically support any new SP or CU as those are being released.

Thanks for your time and the great work.

**Comment by keif888** [comment]
Yes, any service pack on a version of SQL Server that is supported will work.

Third party SSIS components should work without changes with any service pack to SQL Server, provided that they support that version.

There has been no issues with service packs on SQL 2005, 2008, 2012, and 2014.
The unit tests that I perform, included in the source repository if you are interested, whilst developing are executed against SQL Server 2016 SP1.

As with any deployment I strongly recommend testing within your environment to ensure that an unforeseen item doesn't crop up.  (Like the current issue with SSDT 17.2).
Keith

**Comment by jbargallo** [comment]
That was fast, thanks!
